curl -O https://www.cozynet.org/links/banners/yukinu.gif
curl -O https://www.cozynet.org/links/banners/alienozi.png
curl -O https://www.cozynet.org/links/banners/fenix.png
curl -O https://www.cozynet.org/links/banners/tinfoil-hat.png
curl -O https://www.cozynet.org/links/banners/nightt.gif
curl -O https://www.cozynet.org/links/banners/aiws.png
curl -O https://www.cozynet.org/links/banners/jakesthoughts.gif
curl -O https://www.cozynet.org/links/banners/jakes-mail.gif
curl -O https://www.cozynet.org/links/banners/getimiskon.png
curl -O https://www.cozynet.org/links/banners/mayvaneday-org.png
curl -O https://www.cozynet.org/links/banners/se7en-site.png
curl -O https://www.cozynet.org/links/banners/lich.png
curl -O https://www.cozynet.org/links/banners/radio-chupacabra.png
curl -O https://www.cozynet.org/links/banners/uwcur.png
curl -O https://www.cozynet.org/links/banners/saltorn.png
curl -O https://www.cozynet.org/links/banners/parnell.png
curl -O https://www.cozynet.org/links/banners/deurist.png
curl -O https://www.cozynet.org/links/banners/tohya.png
curl -O https://www.cozynet.org/links/banners/kyubit.png
curl -O https://www.cozynet.org/links/banners/grafo.png
curl -O https://www.cozynet.org/links/banners/sftn.png
curl -O https://www.cozynet.org/links/banners/lilibyte.gif
curl -O https://www.cozynet.org/links/banners/strlst.png
curl -O https://www.cozynet.org/links/banners/slime-net.gif
curl -O https://www.cozynet.org/links/banners/bendersteed.jpg
curl -O https://www.cozynet.org/links/banners/the-swiss-bay.jpg
curl -O https://www.cozynet.org/links/banners/six10.png
curl -O https://www.cozynet.org/links/banners/jack91.gif
curl -O https://www.cozynet.org/links/banners/flammable-duck.png
curl -O https://www.cozynet.org/links/banners/gap-and-friends.png
curl -O https://www.cozynet.org/links/banners/purplevoid.png
curl -O https://www.cozynet.org/links/banners/unix-tirol.png
curl -O https://www.cozynet.org/links/banners/shrine-of-hakase.gif
curl -O https://www.cozynet.org/links/banners/extramundane.jpg
curl -O https://www.cozynet.org/links/banners/omicron-setup.gif
curl -O https://www.cozynet.org/links/banners/workingsea.png
curl -O https://www.cozynet.org/links/banners/lukes-cabin.png
curl -O https://www.cozynet.org/links/banners/protocol7.png
curl -O https://www.cozynet.org/links/banners/tard-zone.gif
curl -O https://www.cozynet.org/links/banners/beedge.png
curl -O https://www.cozynet.org/links/banners/0x1bi.png
curl -O https://www.cozynet.org/links/banners/dead-end-shrine.png
curl -O https://www.cozynet.org/links/banners/digilord.gif
curl -O https://www.cozynet.org/links/banners/godcock.jpg
curl -O https://www.cozynet.org/links/banners/michi.png
curl -O https://www.cozynet.org/links/banners/erratas.gif
curl -O https://www.cozynet.org/links/banners/no-sleep.png
curl -O https://www.cozynet.org/links/banners/room-4.jpg
curl -O https://www.cozynet.org/links/banners/hen6003.png
curl -O https://www.cozynet.org/links/banners/slushbin.gif
curl -O https://www.cozynet.org/links/banners/mm4rk3t.gif
curl -O https://www.cozynet.org/links/banners/kassy.jpg
curl -O https://www.cozynet.org/links/banners/cabbage-sorter.png
curl -O https://www.cozynet.org/links/banners/xiixiixii.gif
curl -O https://www.cozynet.org/links/banners/oedo808.gif
curl -O https://www.cozynet.org/links/banners/xn-neko.gif
curl -O https://www.cozynet.org/links/banners/jole.png
curl -O https://www.cozynet.org/links/banners/confusion.png
curl -O https://www.cozynet.org/links/banners/morituri-te-salutant.jpg
curl -O https://www.cozynet.org/links/banners/oversteer.png
curl -O https://www.cozynet.org/links/banners/lain-la.png
curl -O https://www.cozynet.org/links/banners/arisu-world.png
curl -O https://www.cozynet.org/links/banners/unpop.gif
curl -O https://www.cozynet.org/links/banners/driftt.png
curl -O https://www.cozynet.org/links/banners/chaox.png
curl -O https://www.cozynet.org/links/banners/cached-world.png
curl -O https://www.cozynet.org/links/banners/evergreen.png
curl -O https://www.cozynet.org/links/banners/mazak.png
curl -O https://www.cozynet.org/links/banners/small-thoughts.jpg
curl -O https://www.cozynet.org/links/banners/spectrum-of-consciousness.gif
curl -O https://www.cozynet.org/links/banners/liberty-witch.png
curl -O https://www.cozynet.org/links/banners/seapunk.gif
curl -O https://www.cozynet.org/links/banners/ty3r0x.png
curl -O https://www.cozynet.org/links/banners/lckdscl.png
curl -O https://www.cozynet.org/links/banners/qmaury.jpg
curl -O https://www.cozynet.org/links/banners/sizeofcat.jpeg
curl -O https://www.cozynet.org/links/banners/galladite.gif
curl -O https://www.cozynet.org/links/banners/halogen-stars.png
curl -O https://www.cozynet.org/links/banners/kirillov.png
curl -O https://www.cozynet.org/links/banners/nerdbox.png
curl -O https://www.cozynet.org/links/banners/orizuru.png
curl -O https://www.cozynet.org/links/banners/rain.png
curl -O https://www.cozynet.org/links/banners/tocxjo.gif
curl -O https://www.cozynet.org/links/banners/ophanim.gif
curl -O https://www.cozynet.org/links/banners/new-digital-era.png
curl -O https://www.cozynet.org/links/banners/adacayiseverim.png
curl -O https://www.cozynet.org/links/banners/kati.gif
curl -O https://www.cozynet.org/links/banners/heimdall.gif
curl -O https://www.cozynet.org/links/banners/minugahana.png
curl -O https://www.cozynet.org/links/banners/korosama.gif
curl -O https://www.cozynet.org/links/banners/nomadalgia.gif
curl -O https://www.cozynet.org/links/banners/urof.gif
curl -O https://www.cozynet.org/links/banners/thecrypt.gif
curl -O https://www.cozynet.org/links/banners/cosmica123.png
curl -O https://www.cozynet.org/links/banners/cozynet.gif
curl -O https://www.cozynet.org/links/banners/tyxton.png
curl -O https://www.cozynet.org/links/banners/s-config.png
curl -O https://www.cozynet.org/links/banners/interloper.png
curl -O https://www.cozynet.org/links/banners/letsdecentralize.gif
curl -O https://www.cozynet.org/links/banners/FJL.png
curl -O https://www.cozynet.org/links/banners/cool-website.png
curl -O https://www.cozynet.org/links/banners/catgirlvomit.png
curl -O https://www.cozynet.org/links/banners/foreverlikethis.gif
curl -O https://www.cozynet.org/links/banners/the-arcade.gif
curl -O https://www.cozynet.org/links/banners/mouseservices.png
curl -O https://www.cozynet.org/links/banners/vd1r.png
curl -O https://www.cozynet.org/links/banners/sadgirlsclub.png
curl -O https://www.cozynet.org/links/banners/neetventures.gif
curl -O https://www.cozynet.org/links/banners/seththyer.gif
