curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmb10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbsy10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbsy5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbsy6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbsy7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbsy8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbsy9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbx10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbx12.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbx5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbx6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbx7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbx8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbx9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbxsl10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmbxti10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmcsc10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmcsc8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmcsc9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmdunh10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmex10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmex7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmex8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmex9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmff10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmfi10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmfib8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cminch.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmitt10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmi10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmi12.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmi5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmi6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmi7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmi8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmi9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmib10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmib5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmib6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmib7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmib8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmmib9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmr10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmr12.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmr17.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmr5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmr6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmr7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmr8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmr9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmsl10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmsl12.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmsl8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmsl9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmsltt10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmss10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmss12.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmss17.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmss8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmss9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmssbx10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmssdc10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmssi10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmssi12.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmssi17.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmssi8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmssi9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmssq8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmssqi8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmsy10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmsy5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmsy6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmsy7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmsy8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmsy9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmtcsc10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmtex10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmtex8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmtex9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmti10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmti12.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmti7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmti8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmti9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmtt10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmtt12.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmtt8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmtt9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmu10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/cmvtt10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/euex10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/euex7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/euex8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/euex9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eufb10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eufb5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eufb6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eufb7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eufb8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eufb9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eufm10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eufm5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eufm6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eufm7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eufm8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eufm9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eurb10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eurb5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eurb6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eurb7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eurb8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eurb9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eurm10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eurm5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eurm6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eurm7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eurm8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eurm9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eusb10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eusb5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eusb6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eusb7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eusb8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eusb9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eusm10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eusm5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eusm6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eusm7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eusm8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/eusm9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/lasy10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/lasy5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/lasy6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/lasy7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/lasy8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/lasy9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/lasyb10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/lcmss8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/lcmssb8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/lcmssi8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/msam10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/msam5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/msam6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/msam7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/msam8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/msam9.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/msbm10.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/msbm5.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/msbm6.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/msbm7.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/msbm8.otf
curl -LO https://mirrors.ibiblio.org/CTAN/fonts/cm/ps-type1/bakoma/otf/msbm9.otf
